### ISSUE TITLE
IRegistrationconvention Process (v. 3) vs. ScanTypes (v. 4)

### ISSUE THREAD

**Issue by mattdunndc** [MattHoneycutt/Fail-Tracker#7]
Hi Matt,

The latest version of StructureMap implements Process in the ControllerConvention class.
How do I implement Scantypes(TypeSet types, Registry registry) with the newest version of StructureMap?

Thanks in advance.

**Comment by mattdunndc** [comment]
Something like this...

 public void ScanTypes(TypeSet types, Registry registry)
        {
            // Only work on concrete types
            types.FindTypes(TypeClassification.Concretes | TypeClassification.Closed).Each(type =>
            {
                // Register against all the interfaces implemented
                // by this concrete class
                type.GetInterfaces().Each(@interface => registry.For(@interface).Use(type));
            });
        }

**Comment by MattHoneycutt** [comment]
Here's an updated ControllerConvention class from the Heroic.Web.IoC framework: https://github.com/MattHoneycutt/HeroicFramework/blob/master/Heroic.Web.IoC/ControllerConvention.cs

I hope that helps!
