### ISSUE TITLE
ApplicationDbContext getting created multiple times per request

### ISSUE THREAD

**Issue by luisgizirian** [MattHoneycutt/Fail-Tracker#8]
During the PS course, you show how to get a single creation/dispose thanks to the Container-Per-Request pattern.

**But**, cloning this repo, overriding Dispose (exactly as you show), setting up breakpoints (exactly as you show) and running the site, I get these latter to being hit several times per request.

_(although the creation & dispose is correctly balanced)_

Am I missing something or there's something going on here?

**Comment by MattHoneycutt** [comment]
Are you hitting the Accounts controller?  If so, that one is intentionally _not_ set up to use IoC to illustrate what happens without a container-per-request, so a request to it will indeed cause multiple contexts to be created.

**Comment by luisgizirian** [comment]
You're right @MattHoneycutt! Sorry about that.
